### ISSUE TITLE
Dockerfile fails to build in step 14

### ISSUE THREAD

**Issue by anandgavai** [xtermi2/kibana-searchguard#3]
I think this path is not correct or the resource are moved ?

**Comment by xtermi2** [comment]
The path is correct, but there is a general issue with maven central. I'm getting a "502 Bad Gateway" when browsing to https://search.maven.org. I'm quite sure this is a temporary problem. Once the maven central guys fix this, the build of this image will work again.

**Comment by anandgavai** [comment]
Thanks !

**Comment by xtermi2** [comment]
maven central is back to normal
